### ISSUE TITLE
ServiceMeshMemberRoll stops updating

### ISSUE THREAD

**Issue by ryandawsonuk** [Maistra/istio#103]
I installed the OpenShift mesh operator, v1.1.0 on an openshift 4.3.9 cluster. Initially everything seemed to work and I got the bookinfo demo working as well as a project in a second namespace. But then the memberroll stopped updating. I ended up with:
```
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"maistra.io/v1","kind":"ServiceMeshMemberRoll","metadata":{"annotations":{},"finalizers":["maistra.io/istio-operator"],"name":"default","namespace":"istio-system"},"spec":{"members":["seldon","bookinfo","seldon-system"]}}
  selfLink: /apis/maistra.io/v1/namespaces/istio-system/servicemeshmemberrolls/default
  resourceVersion: '8137725'
  name: default
  uid: 371391c3-07ba-4aad-b308-5c034062e688
  creationTimestamp: '2020-04-08T16:17:37Z'
  generation: 12
  namespace: istio-system
  ownerReferences:
    - apiVersion: maistra.io/v1
      kind: ServiceMeshControlPlane
      name: basic-install
      uid: f80bb366-f5f5-4c36-b437-88908082ed7f
  finalizers:
    - maistra.io/istio-operator
spec:
  members:
    - bookinfo
    - seldon
    - seldon-system
status:
  annotations:
    configuredMemberCount: 2/2
  conditions:
    - lastTransitionTime: '2020-04-09T06:47:11Z'
      message: All namespaces have been configured successfully
      reason: Configured
      status: 'True'
      type: Ready
  configuredMembers:
    - bookinfo
    - seldon
  meshGeneration: 1
  meshReconciledVersion: 1.1.0-9.el8-1
  observedGeneration: 4
```
That `lastTransitionTime` is two weeks ago. Even if I remove `bookinfo` as a member, it still remains in the `configuredMembers` and I can still access it through the istio ingress. Adding new members into the member roll does not get them into currentMembers and those projects don't become accessible through ingress. I've tried restarting all the pods in the istio-system namespace but that doesn't bring things to life either. Seems to get stuck somehow.

I then uninstalled the operator and reinstalled it and it worked. Good that it worked but I don't think I should have had to reinstall the operator.

**Comment by luksa** [comment]
@ryandawsonuk thanks for reporting the problem. Any chance you can provide the logs of the Maistra operator?

Also note that bug reports should be filed in our Jira at https://issues.redhat.com/projects/MAISTRA/issues.

**Comment by ryandawsonuk** [comment]
Is that the istio-operator pod in the openshift-operators namespace? Unfortunately I reinstalled it so I now don't have those logs. I guess I'll need to close this and open in jira if I recreate it.
