### ISSUE TITLE
Error applying ServiceMeshPolicy

### ISSUE THREAD

**Issue by jkapl** [Maistra/istio#112]
(NOTE: This is used to report product bugs:
  To report a security vulnerability, please visit <https://istio.io/about/security-vulnerabilities/>
  To ask questions about how to use Istio, please visit <https://discuss.istio.io>
)

**Bug description**

When attempting to apply mTLS ServiceMeshPolicy, API returns: `error: unable to recognize "servicemeshpolicy.yaml": no matches for kind "ServiceMeshPolicy" in version "maistra.io/v1"`

Following these instructions: https://maistra.io/docs/examples/mesh-wide_mtls/

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[x] Docs
[ ] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Expected behavior**

Expect to be able to apply mTLS policy at service mesh control plane level.

**Steps to reproduce the bug**

Apply yaml below in OpenShift 4.3.5 with OpenShift Service Mesh installed via operators.

```
apiVersion: "maistra.io/v1"
kind: "ServiceMeshPolicy"
metadata:
  name: "default"
  namespace: istio-system-test
spec:
  peers:
  - mtls: {}
```

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

Red Hat OpenShift Service Mesh version 1.1.1

**How was Istio installed?**

Operator catalog

**Environment where bug was observed (cloud vendor, OS, etc)**

User provisioned infrastructure on vSphere

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by dgn** [comment]
Hi @jkapl, thanks for the report. We use [Jira](https://issues.redhat.com/projects/MAISTRA) to track issues, please file an issue over there next time.

Luckily, this is just a docs issue. The correct `apiVersion` should be: `authentication.maistra.io/v1`. Sorry for the inconvenience. I'll change the documentation to reflect this.

**Comment by dgn** [comment]
Docs have been corrected. Thank you!
