### ISSUE TITLE
add option to not allow traffic from the router in a tenant namespace

### ISSUE THREAD

**Issue by raffaelespazzoli** [Maistra/istio#127]
(This is used to request new product features, please visit <https://discuss.istio.io> for questions on using Istio)

**Describe the feature request**

currently the network policy created by maistra allow traffic from the router in a tenant namespace as long as a pod as a specific annotation. The RFE is to provide an option in the servicemesh control plane to disable that.
This allow for building service mesh deployment where the tenants traffic is locked and always has to go through ingreess/egreess gateways.

**Describe alternatives you've considered**
remove the ability to create routes via RBAC
prevent from creating pods with the given annotation via OPA.

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Additional context**

**Comment by dgn** [comment]
Closing this as we don't use GitHub issues. If you encounter a bug, please file an issue on our [Red Hat JIRA](https://issues.redhat.com/browse/MAISTRA)
