### ISSUE TITLE
IOR Feature, for TLS Termination configuration.

### ISSUE THREAD

**Issue by David-Elizondo** [Maistra/istio#168]
When using Istio gateway generated Openshift routes. We need the ability to configure the type of TLS termination created. Currently, this Defaults to passthrough termination here: https://github.com/maistra/istio/blob/maistra-2.0/pilot/pkg/config/kube/ior/route.go#L183 . 

My hope is that we can discuss how this is configured and move to a solution. One option is to look for an annotation on the Istio Gateway configuration and depending on its value set the TLS termination type. There may be another way, let's discuss

[ ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Comment by David-Elizondo** [comment]
@dgn @jwendell Just a heads up. I just realized, the new annotation propagation on routes for ACME won't be able to be used until we can configure the route to be Edge terminated.

**Comment by Thesykan** [comment]
How about this, We create annotations on the Istio gateway with the spec below.  


	ior.pilot.maistra.io/TLSTerminationType = {VAL}
	  Allowed Values: {TLSTerminationEdge, TLSTerminationPassthrough, TLSTerminationReencrypt}

	ior.pilot.maistra.io/InsecureEdgeTerminationPolicyType = {VAL}
	  Allowed Values: {InsecureEdgeTerminationPolicyNone, InsecureEdgeTerminationPolicyAllow, InsecureEdgeTerminationPolicyRedirect}

	ior.pilot.maistra.io/TLSCertificateSecret = {VAL}
	  Allowed Values: {ANY} Will correspond to a Secret in the secrets API Controller
	  Expected Secret Properties: {Certificate, Key, CACertificate, DestinationCACertificate}. Should match the definition of v1.TLSConfig properties.

**Comment by dgn** [comment]
Closing this as we don't use GitHub issues. If you encounter a bug, please file an issue on our [Red Hat JIRA](https://issues.redhat.com/browse/MAISTRA)
