### ISSUE TITLE
[Operator] Remove transitive dependency to Operator-SDK from the API

### ISSUE THREAD

**Issue by mhofstetter** [Maistra/istio#171]
**Describe the feature request**
Depending solely on the API of the Maistra Operator (https://github.com/maistra/istio-operator) forces dependent application to handle dependency resolution for the transitive Operator SDK dependency.

The reason for this is because the CRD status has a dependency to the maistra-operator version (`BuildInfo`) (https://github.com/maistra/istio-operator/blob/maistra-2.0/pkg/apis/maistra/status/status.go#L161) and within the init function of the `BuildInfo` the version of the Operator SDK is used (https://github.com/maistra/istio-operator/blob/maistra-2.0/pkg/version/version.go#L43).

It would be great if this indirect dependency could be removed in version 1.1.x and 2.x e.g. by initializing the BuildInfo with the concrete operator sdk version from "externally".

**Describe alternatives you've considered**

Handling the dependency "resolution" in the dependent application (e.g. `go.mod`)

```
replace github.com/operator-framework/operator-sdk => github.com/operator-framework/operator-sdk v0.18.0

replace github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.3+incompatible
```

**Affected product area (please put an X in all that apply)**

Go API

**Comment by dgn** [comment]
I guess we could move reading the SDK version into another package (e.g. main). @rcernich @jwendell wdyt?

**Comment by dgn** [comment]
Closing this as we don't use GitHub issues. If you encounter a bug, please file an issue on our [Red Hat JIRA](https://issues.redhat.com/browse/MAISTRA)
