### ISSUE TITLE
Define PVC size for Elasticsearch deployments

### ISSUE THREAD

**Issue by olaf-meyer** [Maistra/istio#177]
**Describe the feature request**

Sorry, I'm not sure if this is the correct git repository for the question/feature request. During the installation, the user can define the number of Elasticsearch nodes. I haven't found a description how to define the PVC size for the Elasticsearch pods. Is there a way to do that? Altering the PVC size for Elasticsearch could be a bit tricky.

**Describe alternatives you've considered**

**Affected product area (please put an X in all that apply)**

[ ] Configuration Infrastructure
[ ] Docs
[x] Installation
[ ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[ ] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[ ] Multi Control Plane

**Additional context**

**Comment by dgn** [comment]
Closing this as we don't use GitHub issues. If you encounter a bug, please file an issue on our [Red Hat JIRA](https://issues.redhat.com/browse/MAISTRA)
