### ISSUE TITLE
How service mesh to avoid assign a privilege policy

### ISSUE THREAD

**Issue by ericnie2015** [Maistra/istio#179]
I read from istio setup docuement on openshift and it need a privlige container to run on the target namespaces,such as 
oc adm policy add-scc-to-group privileged system:serviceaccounts:<target-namespace>
oc adm policy add-scc-to-group anyuid system:serviceaccounts:<target-namespace>

I find the service mesh on openshift do not needs to do these, my question is do you have more documents or materials about how to avoid the security problems?

Thank you.

**Comment by dgn** [comment]
Closing this as we don't use GitHub issues. If you encounter a bug, please file an issue on our [Red Hat JIRA](https://issues.redhat.com/browse/MAISTRA)
