### ISSUE TITLE
Could you upload images to docker.io for version 1.1.8 ?

### ISSUE THREAD

**Issue by jomeier** [Maistra/istio#181]
Hi,

I tried to install maistra v1.1.8 but there are missing images on docker.io for this version.

The latest available versions on docker.io (mixer, ...) seem to be v1.1.5.

Thank you and greetings,

Josef

**Comment by dgn** [comment]
Closing this as we don't use GitHub issues. If you encounter a bug, please file an issue on our [Red Hat JIRA](https://issues.redhat.com/browse/MAISTRA)
