### ISSUE TITLE
Allow managed network policies in Service Mesh to provide a more clean and secure mesh.

### ISSUE THREAD

**Issue by peterbosalliandercom** [Maistra/istio#204]
We like to have the possibility to manage our own network policies for certain or all namespaces in one service mesh by making it configurable via annotations (i.e. managed_by_maistra: false) on the service mesh member namespace(s) in order to define own managed (by Argocd) netpols. This way we are able to use our own managed (templated with Helm and Argocd) network policies to isolate the namespaces within the mesh and thereby decreasing the overhead by use of multiple meshes, unneeded pods etc  and make it a less complex setup. Furthermore this adds more security within the mesh by making it possible to isolate specific namespaces in the mesh instead of 'trusting' all namespaces within the mesh.

Now there is only one netpol in each member namespace that allows traffic from all mesh namespaces but we like to isolate some of these in the same mesh with the network policies provided by Openshift, this is not possible now. 

Alternative is that we need to create multiple control planes by which for each control plane a new namespace is needed where the mesh pods are running. 10 control planes for example are running 50 pods this does not seem very scalable in a large stretched cluster and gives soon a lot of unneeded overhead. We like to grow our cluster with multiple tenants > 50 of maybe > 100 in the future and we do not want the overhead that comes with the current setup. 

What we like to accomplish is to use one mesh with multiple trusted groups tenants and each tenant has ns-dev, ns-tst, ns-acc, ns-prd, ns-ops namespaces which are isolated from each other on network policy level in the mesh. Everything manged by Argocd and rolled out from one helm template. This seems to work perfectly with a Istio install but is not possible with the Openshift (Maistra) installation. 

We now from Redhat that there are multiple clients asking for this kind of functionality. 

[x ] Configuration Infrastructure
[ ] Docs
[ ] Installation
[x ] Networking
[ ] Performance and Scalability
[ ] Policies and Telemetry
[x] Security
[ ] Test and Release
[ ] User Experience
[ ] Developer Infrastructure

**Affected features (please put an X in all that apply)**

[ ] Multi Cluster
[ ] Virtual Machine
[x] Multi Control Plane

**Additional context**

**Comment by dgn** [comment]
Closing this as we don't use GitHub issues. If you encounter a bug, please file an issue on our [Red Hat JIRA](https://issues.redhat.com/browse/MAISTRA)
