### ISSUE TITLE
Unable to delete SMMR after deleting the SMCP

### ISSUE THREAD

**Issue by tommeramber** [Maistra/istio#222]
I wanted to clean my project so I deleted the SMCP before I deleted the SMMR,
Then I tried to delete the SMMR but I wasn't able to, I also tried to delete the operator, re-install it, create new SMCP, and check the status of the SMMR but it still presents "ErrSMCPMissing" and I'm unable to delete it - the same outcome for force deletion which didn't work.

$ oc get smcp
NAME READY STATUS PROFILES VERSION AGE
basic 9/9 ComponentsReady ["default"] 2.0.0.2 15m
$ oc get smmr
NAME READY STATUS AGE
default 0/1 ErrSMCPMissing 47h
$ oc delete smmr default
servicemeshmemberroll.maistra.io "default" deleted
^C
$ oc delete smmr default --force --grace-period=0
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
servicemeshmemberroll.maistra.io "default" force deleted
^C
$ oc get smmr
NAME READY STATUS AGE
default 0/1 ErrSMCPMissing 47h

**Comment by dgn** [comment]
Hi Tom, we're using JIRA to track bugs, if the problem persists please file an issue in the [MAISTRA project on JIRA](https://issues.redhat.com/browse/MAISTRA). What version of OSSM are you using?

**Comment by tommeramber** [comment]
2.0.1

**Comment by dgn** [comment]
Note that you might have to remove the finalizers from the SMMR manually if you deleted the operator.

Closing this as we don't use GitHub issues. If you encounter a bug, please file an issue on our [Red Hat JIRA](https://issues.redhat.com/browse/MAISTRA)
