### ISSUE TITLE
Rewrite webhook controller tests

### ISSUE THREAD

**Issue by bison** [Maistra/istio#224]
As part of integrating the xns-informers library, we've skipped some unit tests for the webhook controller because they don't work with xns-informers and Maistra doesn't use the webhook controller anyway.

We should look into rewriting these tests. They modify informer caches directly and otherwise do some things that seem to be a bit flaky. It would be nice to not have to disable them, regardless of whether Maistra uses this controller or not.

**Comment by jwendell** [comment]
Please create a Jira for this. We don't use GH issues.

**Comment by jwendell** [comment]
I saw you created https://issues.redhat.com/browse/MAISTRA-2052, closing this one.

**Comment by bison** [comment]
Okay, but I was using this for trying to get the linter to pass. Could you reach out to me before just closing it?

**Comment by jwendell** [comment]
Feel free to reopen this, but I think we should change the linter in this case. We should have remove this issues thing in GH, but I don't know why we didn't do it yet.
