### ISSUE TITLE
RHEL 8 may not be compatible with istio-init

### ISSUE THREAD

**Issue by howardjohn** [Maistra/istio#32]
See https://github.com/istio/istio/issues/15519

**Comment by brian-avery** [comment]
RHEL8 is based on nftables rather than iptables and Istio proxy-init currently doesn't work with it. This has been fixed in Maistra with a proxy-init compatible with iptables for RHEL7 systems and a proxy-init based on nftables which works on RHEL8 systems. We don't yet have an upstream solution.

**Comment by knrc** [comment]
It's not specifically related to RHEL 8 but to what the specific kubernetes distribution relies on for networking, some will be using iptables and others will already have transitioned to nftables.  The RHEL 8 version of iptables translates the configuration through to nftables so will work on distributions which support nftables in preference to iptables.

**Comment by knrc** [comment]
Closing since we already have UBI8 and CNI alternatives to the upstream istio-init
