### ISSUE TITLE
oc explain shows empty description

### ISSUE THREAD

**Issue by rvansa** [Maistra/istio#44]
**Describe the feature request**
When using `oc explain` with custom resources brought by Maistra (e.g. `servicemeshcontrolplane`) this should report the available schema. Now it reports just <empty>.

**Comment by knrc** [comment]
@rvansa Can you please open a jira for this issue?  https://issues.jboss.org/browse/MAISTRA

**Comment by rvansa** [comment]
Moved to https://issues.jboss.org/browse/MAISTRA-762
