### ISSUE TITLE
Spam messages: unstructured.Unstructured ended with: Underlying Result Channel closed 

### ISSUE THREAD

**Issue by bysnupy** [Maistra/istio#46]
**Describe the bug**

istio-galley pod in istio-system logs spam messages as follows
~~~
2019-08-19T09:00:10.186732Z	warn	istio.io/istio/galley/pkg/source/kube/dynamic/source.go:147: watch of *unstructured.Unstructured ended with: Underlying Result Channel closed
~~~

**Expected behavior**
No spam messages

**Steps to reproduce the bug**
It always reproduce without any configuration, it starts logging the spam messages after running istio-galley pod.

**Version**
Red Hat OpenShift Service Mesh 0.12 on OCPv3.11

**Installation**
Istallation steps are based on [Installing the Red Hat OpenShift Service Mesh](https://docs.openshift.com/container-platform/3.11/servicemesh-install/servicemesh-install.html#install_chapter_3).

**Environment**
Bare metal

**Cluster state**
[istio-dump.tar.gz](https://github.com/Maistra/istio/files/3515046/istio-dump.tar.gz)

**Comment by neoisone** [comment]
Can we safely ignore these messages?
As I can see that it just syncs the new and old resource versions.

    111 
    112                 s.handler = handler
    113                 s.informer = cache.NewSharedIndexInformer(
    114                         mlw,
    115                         &unstructured.Unstructured{},
    116                         s.resyncPeriod,
    117                         cache.Indexers{})
    118 
    119                 s.informer.AddEventHandler(cache.ResourceEventHandlerFuncs{
    120                         AddFunc: func(obj interface{}) { s.handleEvent(resource.Added, obj) },
    121                         UpdateFunc: func(old, new interface{}) {
    122                                 newRes := new.(*unstructured.Unstructured)
    123                                 oldRes := old.(*unstructured.Unstructured)
    124                                 if newRes.GetResourceVersion() == oldRes.GetResourceVersion() {
    125                                         // Periodic resync will send update events for all known resources.
    126                                         // Two different versions of the same resource will always have different RVs.
    127                                         return
    128                                 }
    129                                 s.handleEvent(resource.Updated, new)
    130                         },
    131                         DeleteFunc: func(obj interface{}) { s.handleEvent(resource.Deleted, obj) },
    132                 })
    133 
    134                 // Send the an event after the cache syncs.
    135                 go func() {
    136                         _ = cache.WaitForCacheSync(ctx.Done(), s.informer.HasSynced)
    137                         handler(resource.FullSyncEvent)
    138                 }()
    139 
    140                 // Start CRD shared informer and wait for it to exit.
    141                 s.informer.Run(ctx.Done())
    142         })
