### ISSUE TITLE
ServiceMeshControlPlane should not remove an active ingress Deployment object when resources are adjusted

### ISSUE THREAD

**Issue by greg-caffeine** [Maistra/istio#514]
### Bug Description

After increasing the resources.requests.memory value on my default Istio Ingress Gateway, the ServiceMeshControlPlane deleted the entire Ingress Gateway Deployment due to the resources.requests.memory value being in excess of the internal default resources.limits.memory value.  When a configuration change is made to ask for more of a given resources, the available resources should never go to 0.

The reason reported by the ServiceMeshControlPlane was:
`Error processing component istio-ingress: Deployment.apps "istio-ingressgateway" is invalid: spec.template.spec.containers[0].resources.requests: Invalid value: "2Gi": must be less than or equal to memory limit: error: Deployment.apps "istio-ingressgateway" is invalid: spec.template.spec.containers[0].resources.requests: Invalid value: "2Gi": must be less than or equal to memory limit
`
If a live valid deployment configuration is changed to an invalid configuration, the ServiceMeshControlPlane should do nothing rather than delete the live ingress.

### Version

```prose
% istioctl version
1.12.0

% oc version
Client Version: 4.8.0-202111041632.p0.git.88e7eba.assembly.stream-88e7eba
Server Version: 4.8.21
Kubernetes Version: v1.21.5+6a39d04

% helm version --short
v3.8.2+g6e3701e
```

### Additional Information

Steps to reproduce:
On an existing maistra.io/v2 ServiceMeshControlPlane object, set:
    `spec.gateways.ingress.runtime.container.resources.requests.memory: 1Gi`
Once the change is fully deployed, set:
    `spec.gateways.ingress.runtime.container.resources.requests.memory: 2Gi`
The entire default istio-ingressgateway Deployment will be deleted, taking down ingress for the entire cluster.

### Affected product area

- [ ] Docs
- [ ] Installation
- [ ] Networking
- [X] Performance and Scalability
- [ ] Extensions and Telemetry
- [ ] Security
- [ ] Test and Release
- [ ] User Experience
- [ ] Developer Infrastructure
- [ ] Upgrade
- [ ] Multi Cluster
- [ ] Virtual Machine
- [X] Control Plane Revisions

### Is this the right place to submit this?

- [X] This is not a security vulnerability
- [X] This is not a question about how to use Istio

**Comment by luksa** [comment]
@greg-caffeine thank you for reporting this. I've filed an issue [1] in our Jira, which is where track issues. Please check the Jira for updates of this issue.

[1] https://issues.redhat.com/browse/OSSM-1449
