### ISSUE TITLE
Add property to enable/disable mixer spans

### ISSUE THREAD

**Issue by rgordill** [Maistra/istio#53]
**Describe the feature request**
There should be a tracer property to remove trace_zipkin_url parameter, as referenced in https://istio.io/faq/distributed-tracing/#why-mixer-spans.

**Describe alternatives you've considered**
In https://github.com/Maistra/istio/blob/maistra-1.1/install/kubernetes/helm/istio/charts/mixer/templates/deployment.yaml#L54-L58, a property check should be added before to avoid adding this parameter if the mixer spans are not desired in traces.

**Additional context**

**Comment by dgn** [comment]
Closing this as we don't use GitHub issues. If you encounter a bug, please file an issue on our [Red Hat JIRA](https://issues.redhat.com/browse/MAISTRA)
