### ISSUE TITLE
RPM binaries and documentation for Istio mesh expansion

### ISSUE THREAD

**Issue by vadimeisenbergibm** [Maistra/istio#54]
**Describe the feature request**
I would like to perform mesh expansion as described here https://istio.io/docs/examples/mesh-expansion/multi-network/. Is it documented somewhere for the Red Hat service mesh? Where can I get RPM binaries, instead of Debian ones used in the Istio.io example (https://istio.io/docs/examples/mesh-expansion/multi-network/#setting-up-the-vm)

**Additional context**
A customer requirement.

**Comment by knrc** [comment]
@vadimeisenbergibm This is on our roadmap for the 1.1 release, we do not yet support it in our 1.0 GA release.

**Comment by vadimeisenbergibm** [comment]
@knrc I see, thanks! We have a large customer that needs it, so if you can increase its priority, it would be great.

**Comment by vadimeisenbergibm** [comment]
A related issue in istio/istio https://github.com/istio/istio/issues/9117.

**Comment by dgn** [comment]
Closing this as we don't use GitHub issues. If you encounter a bug, please file an issue on our [Red Hat JIRA](https://issues.redhat.com/browse/MAISTRA)
