### ISSUE TITLE
Question: Any other way than ServiceMeshMemberRoll to add namespaces?

### ISSUE THREAD

**Issue by sohrab-** [Maistra/istio#63]
We are trying to automate the creation/update of namespaces. It is a bit awkward for a script that creates a namespace, to also try to maintain (insert if needed) a list of namespaces in the `default` ServiceMeshMemberRoll. 

Is there any other cleaner mechanism for this? Labels or annotations on the namespace? Additional ServiceMeshMemberRoll objects besides `default`?

**Comment by luksa** [comment]
I'm working on it. See https://github.com/Maistra/istio-operator/pull/250

The idea is to introduce a `ServiceMeshMember` object that you create inside the namespace you want to be a part of the mesh. A controller then updates the `ServiceMeshMemberRoll` accordingly. Deleting the `ServiceMeshMEmber` object removes the namespace from the `ServiceMeshMemberRoll`. 

I'd love it if you could test it out and provide feedback.
