### ISSUE TITLE
Failing to install ServiceMeshControlPlane on OKD version 4.3.0-0 and 4.4.0-0 running kubernetes version v1.17.1

### ISSUE THREAD

**Issue by invent360** [Maistra/istio#76]
**Bug description**
unable to recognize "smcp.yaml": no matches for kind "ServiceMeshControlPlane" in version "maistra.io/v1

**Affected product area (please put an X in all that apply)**
OKD 4.3.0 on AWS

**Expected behavior**

**Steps to reproduce the bug**

**Version (include the output of `istioctl version --remote` and `kubectl version`)**

**How was Istio installed?**
*STEP 1*
Install okd successfully
k8_client_url: https://github.com/openshift/okd/releases/download/4.4.0-0.okd-2020-01-28-022517/openshift-client-mac-4.4.0-0.okd-2020-01-28-022517.tar.gz
ocp_installer_url: https://github.com/openshift/okd/releases/download/4.4.0-0.okd-2020-01-28-022517/openshift-install-mac-4.4.0-0.okd-2020-01-28-022517.tar.gz

OR 

k8_client_url: https://github.com/openshift/okd/releases/download/4.3.0-0.okd-2019-11-15-182656/openshift-client-mac-4.3.0-0.okd-2019-11-15-182656.tar.gz
ocp_installer_url: https://github.com/openshift/okd/releases/download/4.3.0-0.okd-2019-11-15-182656/openshift-install-mac-4.3.0-0.okd-2019-11-15-182656.tar.gz

*STEP 2*
i)  Create oc project
oc adm new-project istio-system
ii) Install catalog sources
     oc apply -f redhat-operators-csc.yaml 

`apiVersion: operators.coreos.com/v1
kind: CatalogSourceConfig
metadata:
  name: redhat-operators-packages
  namespace: openshift-marketplace
spec:
  targetNamespace: openshift-operators
  packages: serverless-operator,servicemeshoperator,kiali-ossm,jaeger-product,elasticsearch-operator
  source: redhat-operators`

&& 

oc apply -f community-operators-csc.yaml

`apiVersion: operators.coreos.com/v1
kind: CatalogSourceConfig
metadata:
  name: community-operators-packages
  namespace: openshift-marketplace
spec:
  targetNamespace: openshift-operators
  packages: knative-eventing-operator,openshift-pipelines-operator,knative-kafka-operator ,strimzi-kafka-operator
  source: community-operators`
iii) Install Servicemesh subscription
oc apply -f subscription.yaml

`---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elastic-search
  namespace: openshift-operators
spec:
  channel: preview
  source: redhat-operators-packages
  name: elasticsearch-operator
  sourceNamespace: openshift-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger
  namespace: openshift-operators
spec:
  channel: stable
  source: redhat-operators-packages
  name: jaeger-product
  sourceNamespace: openshift-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali
  namespace: openshift-operators
spec:
  channel: stable
  source: redhat-operators-packages
  name: kiali-ossm 
  sourceNamespace: openshift-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemesh
  namespace: openshift-operators
spec:
  channel: "1.0"
  source: redhat-operators-packages
  name: servicemeshoperator 
  sourceNamespace: openshift-operators`

iv) Install Servicemesh components
oc apply -f smcp.yaml 
`  apiVersion: maistra.io/v1
  kind: ServiceMeshControlPlane
  metadata:
    name: istio-control-plane
    namespace: istio-system
  spec:
    istio:
      global:
        proxy:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 128Mi
        mtls:
          enabled: true
        disablePolicyChecks: true
        policyCheckFailOpen: false
      gateways:
        istio-egressgateway:
          autoscaleEnabled: true
          autoscaleMin: 1
          autoscaleMax: 5
        istio-ingressgateway:
          autoscaleEnabled: true
          autoscaleMin: 1
          autoscaleMax: 5
        cluster-local-gateway:
          autoscaleEnabled: false
          enabled: true
          labels:
            app: cluster-local-gateway
            istio: cluster-local-gateway
          ports:
            - name: status-port
              port: 15020
            - name: http2
              port: 80
              targetPort: 8080
            - name: https
              port: 443
      mixer:
        enabled: true
        policy:
          autoscaleEnabled: false
        telemetry:
          autoscaleEnabled: false
          resources:
            requests:
              cpu: 100m
              memory: 1G
            limits:
              cpu: 500m
              memory: 4G
      pilot:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        autoscaleEnabled: false
        traceSampling: 100
      kiali:
        enabled: true
        dashboard:
          viewOnlyMode: false
        ingress:
          enabled: true
      grafana:
        enabled: true
      tracing:
        enabled: true
        jaeger:
          template: all-in-one`
&& 

oc apply -f smmr.yaml
`apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
  - default
  - bookinfo`

**Environment where bug was observed (cloud vendor, OS, etc)**
--> okd 4.4.0 and 4.3.0 AWS

Additionally, please consider attaching a [cluster state archive](http://istio.io/help/bugs/#generating-a-cluster-state-archive) by attaching
the dump file to this issue.

**Comment by knrc** [comment]
Can you please add the link to the csc files you are installing?  OKD4 is still in preview and is not currently a platform we support, however we can take a look and see if it is stabilising.

**Comment by invent360** [comment]
Thanks for responding, here are links to the csc files, am not sure if you mean the resource files
https://github.com/redhat-developer-demos/guru-night/blob/master/config/redhat-operators-csc.yaml
https://github.com/redhat-developer-demos/guru-night/blob/master/config/community-operators-csc.yaml
regarding the stability of OKD4, i am fully aware this may not be ready yet, i also was just trying things out. Just to also note that this same installation was very successful on OCP 4.x and i was able to invoke the bookinfo service.

**Comment by knrc** [comment]
Thanks very much for the links.

OCP 4.x is supported and does work, however our experience with 3.x is that OKD tends to have some significant differences and required modifications before it could support the features we depended upon.  It may be that something similar is required for OKD 4.x, we will need to evaluate and work through the differences.

**Comment by dgn** [comment]
Closing this as we don't use GitHub issues. If you encounter a bug, please file an issue on our [Red Hat JIRA](https://issues.redhat.com/browse/MAISTRA)
