### ISSUE TITLE
Help needed: unable to import package "github.com/Maistra/istio/pkg/servicemesh"

### ISSUE THREAD

**Issue by lbcdev** [Maistra/istio#78]
Hi team,

I am trying to import ServiceMeshMemberRoll type in a Go client, but failed.

Go version: go1.13.4 darwin/amd64
The code looks like:

import
maistrav1 "github.com/Maistra/istio/pkg/servicemesh/client/clientset/versioned/typed/servicemesh/v1"
...
type ServiceMeshMemberRollInterface struct {
	V1 *maistrav1.ServiceMeshMemberRollInterface
}

In the go.mod, I added:
	github.com/Maistra/istio v0.0.0-20181105172658-41d45b880a2f // indirect

Did I import the wrong library?

Thanks.
Longbin

**Comment by luksa** [comment]
Hi,

You need to use the canonical name of the package when importing (
istio.io/istio/...):

import maistrav1
"istio.io/istio/pkg/servicemesh/client/clientset/versioned/typed/servicemesh/v1"


In go.mod, you then need the following entries:

require (
 istio.io/istio v1.4.0
)

replace istio.io/istio => github.com/Maistra/istio
v0.0.0-20200107173459-4638b96d0091


Hope this helps
Marko

**Comment by lbcdev** [comment]
Hi Marko,

Thanks for the help. I tried this but istio.io/istio v1.4.0 didn't work in go.mod. The error is:
go: istio.io/istio@v1.4.0: reading istio.io/istio/go.mod at revision v1.4.0: unknown revision v1.4.0

My go version is 1.13.4.  If I use go get istio.io/istio@master, it add a version below:
	istio.io/istio v0.0.0-20200213023612-9fdbf4f32acb // indirect
Then cannot load module:
        module istio.io/istio@latest found (v0.0.0-20200213023612-9fdbf4f32acb), but does not contain package istio.io/istio/pkg/servicemesh/client/clientset/versioned/typed/servicemesh/v1

Is it my go version or did I miss something else?

Thanks,
Longbin

**Comment by luksa** [comment]
Did you add the `replace` line to your `go.mod`?

**Comment by lbcdev** [comment]
Hi Marko,

I forgot to add the replace line and now it works. 
Thank you so much for your time.

Best,
Longbin
