### ISSUE TITLE
Version of Istio corresponds to the version of the maistra

### ISSUE THREAD

**Issue by kinash000** [Maistra/istio#95]
Which version of Istio corresponds to the version of the maistra?
For example, I use Maistra 1.0.7, according to which version of Istio I read the documentation.
I would like to have a version matching page.
 
In openshift documentation 
https://docs.openshift.com/container-platform/4.3/service_mesh/servicemesh-release-notes.html#new-features-red-hat-openshift-service-mesh-1-0-7
version of istio is only mentioned before 1.0.2

**Comment by dgn** [comment]
Hi @kinash000, that is because the Istio 1.1 stream has since seen it's end of life. We're still technically based on 1.1.17, but we're backporting critical security fixes.

**Comment by dgn** [comment]
Closing as this is not an issue. Note that for bug tracking we use JIRA: https://issues.redhat.com/projects/MAISTRA
