### ISSUE TITLE
How to use self-signed for jwksUri and issuer in a Policy

### ISSUE THREAD

**Issue by bartoszmajsak** [Maistra/istio#99]
@olaf-meyer commented on [Mon Apr 06 2020](https://github.com/Maistra/istio-workspace/issues/413)

##### Issue Overview

I'm sorry, but I'm not sure whether this is the correct place to open this issue. However, I'm running an OpenShift cluster with a self-signed certificate. My application is using a Keycloak server running on this OpenShift cluster for authentication. If I create a Policy that points to this Keycloak server in the attributes `jwksUri` and `issuer`, I get the following error in the Istio-pilot pod (in the discovery container):

```bash 
2020-02-17T12:57:34.675759Z	error	model	Failed to fetch public key from "https://keycloak-olaf-sso.apps.acme.de/auth/realms/customer/protocol/openid-connect/certs": Get https://keycloak-olaf-sso.apps.acme.de/auth/realms/customer/protocol/openid-connect/certs: x509: certificate signed by unknown authority
2020-02-17T12:57:34.675778Z	warn	Failed to fetch jwt public key from "https://keycloak-olaf-sso.apps.acme.de/auth/realms/customer/protocol/openid-connect/certs"
```
If I mount a secret with my signer CA public certificate (with the file name `cert.pem`)  in the path `/etc/pki/tls/` of the Istio pilot, then my application is running.

##### Current Behaviour

Is overwriting the file `/etc/pki/tls/cert.pem` in the Istio pilot container the correct way to add a self-signed certificate to the Istio pilot. How can I ensure that this certificate is still used after an version update of Pilot image by the Istio Operator? Would it make sense to have an attribute in the resource ServiceMeshControlPlane for this purpose?

**Comment by bartoszmajsak** [comment]
@knrc I moved it from `Istio Workspace` project.

**Comment by dgn** [comment]
In OSSM 1.0, mounting the cert into the container is the only way to make this work. In OSSM 1.1, there will be a field in the SMCP to add a trusted root certificate (`spec.istio.pilot.jwksResolverExtraRootCA`)

**Comment by olaf-meyer** [comment]
Thank you very much for the clarification.

**Comment by srinivma1** [comment]
With OCP 4.3 using service mesh 1.1, Is this field spec.istio.pilot.jwksResolverExtraRootCA added now?

**Comment by dgn** [comment]
> With OCP 4.3 using service mesh 1.1, Is this field spec.istio.pilot.jwksResolverExtraRootCA added now?

Yes
